### PR TITLE
Uploader status update

### PR DESCRIPTION
**Pull request by samsep**
ping @aselbie

### CODE REVIEW

**Comment by aselbie** [comment]
I think we want to keep the actual styling out of this repo. The idea with adding the classes to file view was so that it could be styled in an external source. These changes might be appropriate for ``work-styles``, but otherwise would probably go in the ``submit-work.scss`` in ``work-app``.

Thinking about the logic for the overall uploader status a bit more I think we may want to separate it into a couple variables, rather than try to jam everything into one. I think we may want:

```
uploading: true|false
hasErrors: true|false
```

And then the logic in work-app for whether or not to submit would becomes ``if (!uploading && !hasErrors``. I'm going to check with Anuj, but I'm guessing that we're not going to want to allow users to submit the form if some of their uploads have errored.

**Comment by samsep** [comment]
Makes sense, removed the styles. I can update the variables as part of a new story too.

**Comment by aselbie** [comment]
I think there's still a reference to the CSS file in ``example/index.jade``, but otherwise LGTM.

**Comment by samsep** [comment]
Cool just removed

**Pull request merged**
