### PR TITLE
DEM-879 replace uploader statuses w/ new variables

### PR DESCRIPTION
**Pull request by samsep**
ping @aselbie

### CODE REVIEW

**Comment by aselbie** [comment]
I think the return statements inside the ``onUpdate`` function are going to have unintended consequences. It's possible that we could have both files with errors and files with files that are uploading, and this wouldn't record that depending on the order. The first file we came across that met either of those criteria would update, and then the whole function would return.

We could do something like this instead:

```javascript
var uploading = false;
var hasErrors = false;

for (var i = 0; i < uploader.files.length; i++) {
  if (uploader.files[i].uploading === true) {
    uploading = true;
  } else if (uploader.files[i].hasErrors === true) {
    hasErrors = true;
  }
}

uploader.uploading = uploading;
uploader.hasErrors = hasErrors;
```

This way we go through all the files and set both booleans if necessary.

**Comment by aselbie** [comment]
Also, I'm aware that build is failing. I'll have to update the repo to use the newer gulp-tasks before it will work.

**Comment by aselbie** [comment]
Otherwise LGTM.

**Comment by samsep** [comment]
Cool, updated the service

**Pull request merged**
